export const sidebarItems = [
  ["لوحة التحكم العامة", "/"],
  ["الفروع", "/branches"],
  ["لوحة الفرع", "/branch-dashboard"],
  ["تأسيس الفرع", "/branch-setup"],
  ["اليومية", "/daily-entry"],
  ["سجل اليوميات", "/daily-entries"],
  ["المشتريات", "/purchases"],
  ["المصروفات", "/expenses"],
  ["الخزنة", "/cashbox"],
  ["الجرد", "/stocktake"],
  ["رأس المال", "/capital"],
  ["التحويلات بين الفروع", "/transfers"],
  ["مقارنة الفروع", "/branch-comparison"],
  ["الدليفريهات", "/delivery-agents"],
  ["الأوردرات", "/orders"],
  ["رحلات الدليفري", "/delivery-runs"],
  ["تسويات الدليفري", "/delivery-settlements"],
  ["تقارير الدليفري", "/delivery-reports"],
  ["التقارير", "/reports"],
  ["التقارير المجمعة", "/consolidated-reports"],
  ["المستخدمون والصلاحيات", "/users"],
  ["الإعدادات", "/settings"]
] as const;
